version: "3.8"

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.27.0.0/16"

services:

  s3:
    image: minio/minio
    networks:
      network:
        ipv4_address: 172.27.0.2
    ports:
      - "9011:9001"
      - "9010:9000"
    volumes:
      - data-s3:/data
    environment:
      MINIO_ROOT_USER: MdnaDEXKy9nOc4beIvNcgy
      MINIO_ROOT_PASSWORD: BjjctVsoSg4FKkT81VKt18
    command: server --address 0.0.0.0:9000 --console-address :9001 /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3

  s3-service:
    image: minio/mc
    networks:
      network:
        ipv4_address: 172.27.0.3
    depends_on:
      s3:
        condition: service_healthy
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set backup http://s3:9000 MdnaDEXKy9nOc4beIvNcgy BjjctVsoSg4FKkT81VKt18;
      /usr/bin/mc mb backup/cb-backup-s3;
      "

volumes:
  data-s3: